name: FlutterGalleryApp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^2.0.0

  cupertino_icons: ^0.1.2
  connectivity: ^0.4.8+6
  gallery_saver: ^2.0.1
  flutter_bloc: 6.0.5
  equatable: 1.2.5
  flutter_svg: 0.19.0
  font_awesome_flutter: 8.8.1



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
